openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for calc
paths:
    /:
        post:
            tags:
                - calc
            summary: divide calc
            operationId: calc#divide
            requestBody:
                description: Request body for divide.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DivideRequestBody'
                        example:
                            dividend: 6599615662108896380
                            divisor: 6289780582187170160
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivideResponseBody'
                            example:
                                quotient: 5026300794991892168
                                reminder: 3251227134896864353
                "400":
                    description: 'div_by_zero: Response used for division by zero errors'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivByZero'
                            example:
                                message: Consequatur veniam est tempora non natus.
                "504":
                    description: 'timeout: Operation timed out'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                            example:
                                fault: false
                                id: 123abc
                                message: parameter 'p' must be an integer
                                name: timeout
                                temporary: false
                                timeout: true
components:
    schemas:
        DivByZero:
            type: object
            properties:
                message:
                    type: string
                    description: division by zero leads to infinity.
                    example: Consequatur veniam est tempora non natus.
            description: DivByZero is the error returned when using value 0 as divisor.
            example:
                message: Consequatur veniam est tempora non natus.
            required:
                - message
        DivideRequestBody:
            type: object
            properties:
                dividend:
                    type: integer
                    example: 6599615662108896380
                    format: int64
                divisor:
                    type: integer
                    example: 6289780582187170160
                    format: int64
            description: Request body for divide.
            example:
                dividend: 6599615662108896380
                divisor: 6289780582187170160
            required:
                - dividend
                - divisor
        DivideResponseBody:
            type: object
            properties:
                quotient:
                    type: integer
                    example: 5026300794991892168
                    format: int64
                reminder:
                    type: integer
                    example: 3251227134896864353
                    format: int64
            example:
                quotient: 5026300794991892168
                reminder: 3251227134896864353
            required:
                - quotient
                - reminder
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Error response result type
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
tags:
    - name: calc
