openapi: 3.0.3
info:
    title: Chatter service describing the streaming features of goa v2.
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for chatter
paths:
    /echoer:
        get:
            tags:
                - chatter
            summary: echoer chatter
            description: Echoes the message sent by the client.
            operationId: chatter#echoer
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Adipisci nihil quis modi quaerat itaque.
                            example: Eum adipisci iusto occaecati rerum earum.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Earum quae fugiat enim.
                            example: Sint consequatur sit cupiditate neque vel sint.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Et architecto est numquam commodi rerum est.
                            example: Nihil sed.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /history:
        get:
            tags:
                - chatter
            summary: history chatter
            description: Returns the chat messages sent to the server.
            operationId: chatter#history
            parameters:
                - name: view
                  in: query
                  description: View to use to render the result
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to use to render the result
                    example: Aut incidunt deserunt est modi earum.
                  example: Aut expedita ea cupiditate dolor.
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GoaSummary'
                            example:
                                length: 5227746826151536988
                                message: Fugit et id cum cum.
                                sent_at: "1978-02-25T14:12:07Z"
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Soluta ipsam cupiditate.
                            example: Et corrupti non.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Et sed.
                            example: Quae dicta repudiandae dolorem ex a voluptatem.
            security:
                - jwt_header_Authorization:
                    - stream:read
    /listener:
        get:
            tags:
                - chatter
            summary: listener chatter
            description: Listens to the messages sent by the client.
            operationId: chatter#listener
            responses:
                "101":
                    description: Switching Protocols response.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Consequuntur cumque id aliquam aliquam.
                            example: Impedit ut odio vel saepe illum iusto.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Velit voluptates enim quo vel modi.
                            example: Inventore ut ut id eveniet eum eveniet.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /login:
        post:
            tags:
                - chatter
            summary: login chatter
            description: Creates a valid JWT token for auth to chat.
            operationId: chatter#login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: New JWT token
                                example: Dolor aperiam doloremque.
                            example: A ut ut aut voluptates sit.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Neque rerum facilis.
                            example: Quisquam deserunt suscipit quia.
            security:
                - basic_header_Authorization: []
    /subscribe:
        get:
            tags:
                - chatter
            summary: subscribe chatter
            description: Subscribe to events sent when new chat messages are added.
            operationId: chatter#subscribe
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Event'
                            example:
                                action: added
                                added_at: "1982-12-11T22:46:57Z"
                                message: Unde ea recusandae.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Sunt sit voluptatibus.
                            example: Voluptatibus sint voluptatem incidunt fugiat odit.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Atque et magnam blanditiis voluptates.
                            example: Nobis nesciunt eaque voluptatibus est sit aut.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /summary:
        get:
            tags:
                - chatter
            summary: summary chatter
            description: Summarizes the chat messages sent by the client.
            operationId: chatter#summary
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatSummaryResponseCollection'
                            example:
                                - length: 1105227772908485323
                                  message: Quidem et sint cupiditate at aut.
                                  sent_at: "1988-11-26T16:43:27Z"
                                - length: 1105227772908485323
                                  message: Quidem et sint cupiditate at aut.
                                  sent_at: "1988-11-26T16:43:27Z"
                                - length: 1105227772908485323
                                  message: Quidem et sint cupiditate at aut.
                                  sent_at: "1988-11-26T16:43:27Z"
                                - length: 1105227772908485323
                                  message: Quidem et sint cupiditate at aut.
                                  sent_at: "1988-11-26T16:43:27Z"
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Et et amet.
                            example: In in ut sint incidunt enim.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aspernatur nulla deleniti.
                            example: Optio fugit sunt quod incidunt.
            security:
                - jwt_header_Authorization:
                    - stream:write
components:
    schemas:
        ChatSummaryResponse:
            type: object
            properties:
                length:
                    type: integer
                    description: Length of the message sent
                    example: 7238520324567891595
                    format: int64
                message:
                    type: string
                    description: Message sent to the server
                    example: Corporis nisi praesentium eaque.
                sent_at:
                    type: string
                    description: Time at which the message was sent
                    example: "1988-04-06T15:46:04Z"
                    format: date-time
            description: ChatSummaryResponse result type (default view)
            example:
                length: 1644665013397551871
                message: Perspiciatis aliquid aut impedit et.
                sent_at: "1979-10-21T06:46:08Z"
            required:
                - message
                - sent_at
        ChatSummaryResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/ChatSummaryResponse'
            description: SummaryResponseBody is the result type for an array of ChatSummaryResponse (default view)
            example:
                - length: 1105227772908485323
                  message: Quidem et sint cupiditate at aut.
                  sent_at: "1988-11-26T16:43:27Z"
                - length: 1105227772908485323
                  message: Quidem et sint cupiditate at aut.
                  sent_at: "1988-11-26T16:43:27Z"
        Event:
            type: object
            properties:
                action:
                    type: string
                    example: added
                    enum:
                        - added
                added_at:
                    type: string
                    description: Time at which the message was added
                    example: "1995-02-24T08:42:47Z"
                    format: date-time
                message:
                    type: string
                    description: Message sent to the server
                    example: Quidem aut est.
            example:
                action: added
                added_at: "2001-10-24T02:08:53Z"
                message: Aut qui qui quo omnis.
            required:
                - message
                - action
                - added_at
        GoaSummary:
            type: object
            properties:
                length:
                    type: integer
                    description: Length of the message sent
                    example: 767232288878080996
                    format: int64
                message:
                    type: string
                    description: Message sent to the server
                    example: Modi quasi ipsa cupiditate itaque.
                sent_at:
                    type: string
                    description: Time at which the message was sent
                    example: "1979-06-19T02:02:38Z"
                    format: date-time
            example:
                length: 3872568260242236993
                message: Corrupti impedit laborum.
                sent_at: "1991-07-21T11:42:29Z"
            required:
                - message
                - sent_at
    securitySchemes:
        basic_header_Authorization:
            type: http
            description: Secures the login endpoint.
            scheme: basic
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".
            scheme: bearer
tags:
    - name: chatter
      description: The chatter service implements a simple client and server chat.
