openapi: 3.0.3
info:
    title: Cellar Service
    description: HTTP service for managing your wine cellar
    version: "1.0"
servers:
    - url: http://localhost:8000/cellar
      description: cellar hosts the storage, sommelier and swagger services.
    - url: https://goa.design/cellar
      description: cellar hosts the storage, sommelier and swagger services.
paths:
    /sommelier:
        post:
            tags:
                - sommelier
            summary: pick sommelier
            operationId: sommelier#pick
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PickRequestBody'
                        example:
                            name: Blue's Cuvee
                            varietal:
                                - pinot noir
                                - merlot
                                - cabernet franc
                            winery: longoria
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredBottleResponseCollection'
                            example:
                                - composition:
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  id: 123abc
                                  name: Blue's Cuvee
                                  rating: 3
                                  vintage: 1941
                                  winery:
                                    name: Longoria
                                - composition:
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  id: 123abc
                                  name: Blue's Cuvee
                                  rating: 3
                                  vintage: 1941
                                  winery:
                                    name: Longoria
                                - composition:
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  id: 123abc
                                  name: Blue's Cuvee
                                  rating: 3
                                  vintage: 1941
                                  winery:
                                    name: Longoria
                                - composition:
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                    - percentage: 82
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  id: 123abc
                                  name: Blue's Cuvee
                                  rating: 3
                                  vintage: 1941
                                  winery:
                                    name: Longoria
                "400":
                    description: 'no_criteria: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Accusamus ut rerum dicta quo.
                "404":
                    description: 'no_match: Not Found response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Optio aspernatur modi.
    /storage:
        get:
            tags:
                - storage
            summary: list storage
            description: List all stored bottles
            operationId: storage#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredBottleResponseTinyCollection'
                            example:
                                - id: 123abc
                                  name: Blue's Cuvee
                                  winery:
                                    name: Longoria
                                - id: 123abc
                                  name: Blue's Cuvee
                                  winery:
                                    name: Longoria
                                - id: 123abc
                                  name: Blue's Cuvee
                                  winery:
                                    name: Longoria
                                - id: 123abc
                                  name: Blue's Cuvee
                                  winery:
                                    name: Longoria
        post:
            tags:
                - storage
            summary: add storage
            description: Add new bottle and return its ID.
            operationId: storage#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            composition:
                                - percentage: 92
                                  varietal: Syrah
                                - percentage: 92
                                  varietal: Syrah
                                - percentage: 92
                                  varietal: Syrah
                                - percentage: 92
                                  varietal: Syrah
                            description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                            name: Blue's Cuvee
                            rating: 1
                            vintage: 1941
                            winery:
                                country: USA
                                name: Longoria
                                region: Central Coast, California
                                url: http://www.longoriawine.com/
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Cumque consequuntur dolorum eos.
                            example: Sit aut officia pariatur.
    /storage/{id}:
        delete:
            tags:
                - storage
            summary: remove storage
            description: Remove bottle from storage
            operationId: storage#remove
            parameters:
                - name: id
                  in: path
                  description: ID of bottle to remove
                  required: true
                  schema:
                    type: string
                    description: ID of bottle to remove
                    example: Qui quia deleniti aut.
                  example: Reprehenderit doloremque.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - storage
            summary: show storage
            description: Show bottle by ID
            operationId: storage#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: default
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of bottle to show
                  required: true
                  schema:
                    type: string
                    description: ID of bottle to show
                    example: Dolores aut.
                  example: Eaque repellat quidem laudantium eaque dignissimos qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                description: 'Response body may alternatively be #/components/schemas/StoredBottleResponseTiny'
                                $ref: '#/components/schemas/StoredBottle'
                            example:
                                composition:
                                    - percentage: 99
                                      varietal: Syrah
                                    - percentage: 99
                                      varietal: Syrah
                                    - percentage: 99
                                      varietal: Syrah
                                description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                id: 123abc
                                name: Blue's Cuvee
                                rating: 4
                                vintage: 1995
                                winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                "404":
                    description: 'not_found: Bottle not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
    /storage/multi_add:
        post:
            tags:
                - storage
            summary: multi_add storage
            description: Add n number of bottles and return their IDs. This is a multipart request and each part has field name 'bottle' and contains the encoded bottle info to be added.
            operationId: storage#multi_add
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/AddRequestBody'
                            example:
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                        example:
                            - composition:
                                - percentage: 92
                                  varietal: Syrah
                                - percentage: 92
                                  varietal: Syrah
                              description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                              name: Blue's Cuvee
                              rating: 1
                              vintage: 1984
                              winery:
                                country: USA
                                name: Longoria
                                region: Central Coast, California
                                url: http://www.longoriawine.com/
                            - composition:
                                - percentage: 92
                                  varietal: Syrah
                                - percentage: 92
                                  varietal: Syrah
                              description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                              name: Blue's Cuvee
                              rating: 1
                              vintage: 1984
                              winery:
                                country: USA
                                name: Longoria
                                region: Central Coast, California
                                url: http://www.longoriawine.com/
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Eius voluptatem.
                                example:
                                    - Laudantium corrupti et.
                                    - Odit modi.
                            example:
                                - Ad officia quia.
                                - Voluptates sequi nam.
                                - Exercitationem nulla mollitia.
                                - Itaque iste quibusdam eius officia quaerat dolor.
    /storage/multi_update:
        put:
            tags:
                - storage
            summary: multi_update storage
            description: Update bottles with the given IDs. This is a multipart request and each part has field name 'bottle' and contains the encoded bottle info to be updated. The IDs in the query parameter is mapped to each part in the request.
            operationId: storage#multi_update
            parameters:
                - name: ids
                  in: query
                  description: IDs of the bottles to be updated
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: array
                    items:
                        type: string
                        example: Nihil doloremque magnam qui aut sed.
                    description: IDs of the bottles to be updated
                    example:
                        - Earum hic aperiam quaerat dolorum et.
                        - Aspernatur a pariatur nesciunt autem adipisci ut.
                        - Porro soluta sapiente ducimus et.
                        - Et fugiat.
                  example:
                    - Dolor mollitia est vel.
                    - Dignissimos est non.
                    - Ipsam tempora hic qui.
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            $ref: '#/components/schemas/MultiUpdateRequestBody'
                        example:
                            bottles:
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
                                - composition:
                                    - percentage: 92
                                      varietal: Syrah
                                    - percentage: 92
                                      varietal: Syrah
                                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                                  name: Blue's Cuvee
                                  rating: 1
                                  vintage: 1984
                                  winery:
                                    country: USA
                                    name: Longoria
                                    region: Central Coast, California
                                    url: http://www.longoriawine.com/
            responses:
                "204":
                    description: No Content response.
    /storage/rate:
        post:
            tags:
                - storage
            summary: rate storage
            description: Rate bottles by IDs
            operationId: storage#rate
            responses:
                "200":
                    description: OK response.
    /swagger/swagger.json:
        get:
            tags:
                - swagger
            summary: Download gen/http/openapi.json
            description: JSON document containing the API swagger definition
            operationId: swagger#/swagger/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        AddRequestBody:
            type: object
            properties:
                composition:
                    type: array
                    items:
                        $ref: '#/components/schemas/Component'
                    description: Composition is the list of grape varietals and associated percentage.
                    example:
                        - percentage: 92
                          varietal: Syrah
                        - percentage: 92
                          varietal: Syrah
                        - percentage: 92
                          varietal: Syrah
                description:
                    type: string
                    description: Description of bottle
                    example: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                    maxLength: 2000
                name:
                    type: string
                    description: Name of bottle
                    example: Blue's Cuvee
                    maxLength: 100
                rating:
                    type: integer
                    description: Rating of bottle from 1 (worst) to 5 (best)
                    example: 1
                    minimum: 1
                    maximum: 5
                vintage:
                    type: integer
                    description: Vintage of bottle
                    example: 1980
                    minimum: 1900
                    maximum: 2020
                winery:
                    $ref: '#/components/schemas/Winery'
            example:
                composition:
                    - percentage: 92
                      varietal: Syrah
                    - percentage: 92
                      varietal: Syrah
                    - percentage: 92
                      varietal: Syrah
                    - percentage: 92
                      varietal: Syrah
                description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                name: Blue's Cuvee
                rating: 1
                vintage: 1909
                winery:
                    country: USA
                    name: Longoria
                    region: Central Coast, California
                    url: http://www.longoriawine.com/
            required:
                - name
                - winery
                - vintage
        Component:
            type: object
            properties:
                percentage:
                    type: integer
                    description: Percentage of varietal in wine
                    example: 81
                    minimum: 1
                    maximum: 100
                varietal:
                    type: string
                    description: Grape varietal
                    example: Syrah
                    pattern: '[A-Za-z'' ]+'
                    maxLength: 100
            example:
                percentage: 75
                varietal: Syrah
            required:
                - varietal
        MultiUpdateRequestBody:
            type: object
            properties:
                bottles:
                    type: array
                    items:
                        $ref: '#/components/schemas/AddRequestBody'
                    description: Array of bottle info that matches the ids attribute
                    example:
                        - composition:
                            - percentage: 92
                              varietal: Syrah
                            - percentage: 92
                              varietal: Syrah
                          description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                          name: Blue's Cuvee
                          rating: 1
                          vintage: 1984
                          winery:
                            country: USA
                            name: Longoria
                            region: Central Coast, California
                            url: http://www.longoriawine.com/
                        - composition:
                            - percentage: 92
                              varietal: Syrah
                            - percentage: 92
                              varietal: Syrah
                          description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                          name: Blue's Cuvee
                          rating: 1
                          vintage: 1984
                          winery:
                            country: USA
                            name: Longoria
                            region: Central Coast, California
                            url: http://www.longoriawine.com/
                        - composition:
                            - percentage: 92
                              varietal: Syrah
                            - percentage: 92
                              varietal: Syrah
                          description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                          name: Blue's Cuvee
                          rating: 1
                          vintage: 1984
                          winery:
                            country: USA
                            name: Longoria
                            region: Central Coast, California
                            url: http://www.longoriawine.com/
                        - composition:
                            - percentage: 92
                              varietal: Syrah
                            - percentage: 92
                              varietal: Syrah
                          description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                          name: Blue's Cuvee
                          rating: 1
                          vintage: 1984
                          winery:
                            country: USA
                            name: Longoria
                            region: Central Coast, California
                            url: http://www.longoriawine.com/
            example:
                bottles:
                    - composition:
                        - percentage: 92
                          varietal: Syrah
                        - percentage: 92
                          varietal: Syrah
                      description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                      name: Blue's Cuvee
                      rating: 1
                      vintage: 1984
                      winery:
                        country: USA
                        name: Longoria
                        region: Central Coast, California
                        url: http://www.longoriawine.com/
                    - composition:
                        - percentage: 92
                          varietal: Syrah
                        - percentage: 92
                          varietal: Syrah
                      description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                      name: Blue's Cuvee
                      rating: 1
                      vintage: 1984
                      winery:
                        country: USA
                        name: Longoria
                        region: Central Coast, California
                        url: http://www.longoriawine.com/
                    - composition:
                        - percentage: 92
                          varietal: Syrah
                        - percentage: 92
                          varietal: Syrah
                      description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                      name: Blue's Cuvee
                      rating: 1
                      vintage: 1984
                      winery:
                        country: USA
                        name: Longoria
                        region: Central Coast, California
                        url: http://www.longoriawine.com/
            required:
                - bottles
        NotFound:
            type: object
            properties:
                id:
                    type: string
                    description: ID of missing bottle
                    example: Et vitae libero quis non soluta.
                message:
                    type: string
                    description: Message of error
                    example: bottle 1 not found
            description: Bottle not found
            example:
                id: Tempora nobis quia.
                message: bottle 1 not found
            required:
                - message
                - id
        PickRequestBody:
            type: object
            properties:
                name:
                    type: string
                    description: Name of bottle to pick
                    example: Blue's Cuvee
                varietal:
                    type: array
                    items:
                        type: string
                        example: Amet facere consequatur ut explicabo libero.
                    description: Varietals in preference order
                    example:
                        - pinot noir
                        - merlot
                        - cabernet franc
                winery:
                    type: string
                    description: Winery of bottle to pick
                    example: longoria
            example:
                name: Blue's Cuvee
                varietal:
                    - pinot noir
                    - merlot
                    - cabernet franc
                winery: longoria
        StoredBottle:
            type: object
            properties:
                composition:
                    type: array
                    items:
                        $ref: '#/components/schemas/Component'
                    description: Composition is the list of grape varietals and associated percentage.
                    example:
                        - percentage: 99
                          varietal: Syrah
                        - percentage: 99
                          varietal: Syrah
                        - percentage: 99
                          varietal: Syrah
                description:
                    type: string
                    description: Description of bottle
                    example: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                    maxLength: 2000
                id:
                    type: string
                    description: ID is the unique id of the bottle.
                    example: 123abc
                name:
                    type: string
                    description: Name of bottle
                    example: Blue's Cuvee
                    maxLength: 100
                rating:
                    type: integer
                    description: Rating of bottle from 1 (worst) to 5 (best)
                    example: 4
                    minimum: 1
                    maximum: 5
                vintage:
                    type: integer
                    description: Vintage of bottle
                    example: 1920
                    minimum: 1900
                    maximum: 2020
                winery:
                    $ref: '#/components/schemas/Winery'
            example:
                composition:
                    - percentage: 99
                      varietal: Syrah
                    - percentage: 99
                      varietal: Syrah
                    - percentage: 99
                      varietal: Syrah
                description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                id: 123abc
                name: Blue's Cuvee
                rating: 4
                vintage: 1925
                winery:
                    country: USA
                    name: Longoria
                    region: Central Coast, California
                    url: http://www.longoriawine.com/
            required:
                - id
                - name
                - winery
                - vintage
        StoredBottleResponse:
            type: object
            properties:
                composition:
                    type: array
                    items:
                        $ref: '#/components/schemas/Component'
                    description: Composition is the list of grape varietals and associated percentage.
                    example:
                        - percentage: 82
                          varietal: Syrah
                        - percentage: 82
                          varietal: Syrah
                        - percentage: 82
                          varietal: Syrah
                description:
                    type: string
                    description: Description of bottle
                    example: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                    maxLength: 2000
                id:
                    type: string
                    description: ID is the unique id of the bottle.
                    example: 123abc
                name:
                    type: string
                    description: Name of bottle
                    example: Blue's Cuvee
                    maxLength: 100
                rating:
                    type: integer
                    description: Rating of bottle from 1 (worst) to 5 (best)
                    example: 4
                    minimum: 1
                    maximum: 5
                vintage:
                    type: integer
                    description: Vintage of bottle
                    example: 2018
                    minimum: 1900
                    maximum: 2020
                winery:
                    $ref: '#/components/schemas/WineryResponseTiny'
            description: A StoredBottle describes a bottle retrieved by the storage service. (default view)
            example:
                composition:
                    - percentage: 82
                      varietal: Syrah
                    - percentage: 82
                      varietal: Syrah
                description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                id: 123abc
                name: Blue's Cuvee
                rating: 2
                vintage: 1902
                winery:
                    name: Longoria
            required:
                - id
                - name
                - winery
                - vintage
        StoredBottleResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredBottleResponse'
            description: PickResponseBody is the result type for an array of StoredBottleResponse (default view)
            example:
                - composition:
                    - percentage: 82
                      varietal: Syrah
                    - percentage: 82
                      varietal: Syrah
                    - percentage: 82
                      varietal: Syrah
                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                  id: 123abc
                  name: Blue's Cuvee
                  rating: 3
                  vintage: 1941
                  winery:
                    name: Longoria
                - composition:
                    - percentage: 82
                      varietal: Syrah
                    - percentage: 82
                      varietal: Syrah
                    - percentage: 82
                      varietal: Syrah
                  description: Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah
                  id: 123abc
                  name: Blue's Cuvee
                  rating: 3
                  vintage: 1941
                  winery:
                    name: Longoria
        StoredBottleResponseTiny:
            type: object
            properties:
                id:
                    type: string
                    description: ID is the unique id of the bottle.
                    example: 123abc
                name:
                    type: string
                    description: Name of bottle
                    example: Blue's Cuvee
                    maxLength: 100
                winery:
                    $ref: '#/components/schemas/WineryResponseTiny'
            description: A StoredBottle describes a bottle retrieved by the storage service. (tiny view)
            example:
                id: 123abc
                name: Blue's Cuvee
                winery:
                    name: Longoria
            required:
                - id
                - name
                - winery
        StoredBottleResponseTinyCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredBottleResponseTiny'
            description: ListResponseBody is the result type for an array of StoredBottleResponse (tiny view)
            example:
                - id: 123abc
                  name: Blue's Cuvee
                  winery:
                    name: Longoria
                - id: 123abc
                  name: Blue's Cuvee
                  winery:
                    name: Longoria
                - id: 123abc
                  name: Blue's Cuvee
                  winery:
                    name: Longoria
                - id: 123abc
                  name: Blue's Cuvee
                  winery:
                    name: Longoria
        Winery:
            type: object
            properties:
                country:
                    type: string
                    description: Country of winery
                    example: USA
                    pattern: '[a-zA-Z ''\.]+'
                name:
                    type: string
                    description: Name of winery
                    example: Longoria
                region:
                    type: string
                    description: Region of winery
                    example: Central Coast, California
                    pattern: '[a-zA-Z ''\.]+'
                url:
                    type: string
                    description: Winery website URL
                    example: http://www.longoriawine.com/
                    pattern: ^(https?|ftp)://[^\s/$.?#].[^\s]*$
            example:
                country: USA
                name: Longoria
                region: Central Coast, California
                url: http://www.longoriawine.com/
            required:
                - name
                - region
                - country
        WineryResponseTiny:
            type: object
            properties:
                name:
                    type: string
                    description: Name of winery
                    example: Longoria
            description: WineryResponse result type (tiny view)
            example:
                name: Longoria
            required:
                - name
tags:
    - name: sommelier
      description: The sommelier service retrieves bottles given a set of criteria.
    - name: storage
      description: The storage service makes it possible to view, add or remove wine bottles.
    - name: swagger
      description: The swagger service serves the API swagger definition.
