openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for interceptors
paths:
    /records/{tenantID}:
        post:
            tags:
                - interceptors
            summary: create interceptors
            description: Create a new record with all interceptors in action
            operationId: interceptors#create
            parameters:
                - name: tenantID
                  in: path
                  description: Tenant ID for the request
                  required: true
                  schema:
                    type: string
                    description: Tenant ID for the request
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                  example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                - name: Authorization
                  in: header
                  description: JWT auth token
                  required: true
                  schema:
                    type: string
                    description: JWT auth token
                    example: Eaque repellendus quo blanditiis rerum harum.
                  example: Eaque repellendus quo blanditiis rerum harum.
            requestBody:
                description: Request body for create.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                            traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                            value: Vel dolores.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                duration: 3718795145732531204
                                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                                processedAt: Dolor sit.
                                retryCount: 5419496228293178792
                                retryDuration: 9203795670612989877
                                status: 4185462404774819293
                                tenant: Dolores sunt non.
                                value: Minima eos voluptate esse dolores assumenda.
    /records/{tenantID}/{recordID}:
        get:
            tags:
                - interceptors
            summary: get interceptors
            description: Get retrieves a record by ID with all interceptors in action
            operationId: interceptors#get
            parameters:
                - name: tenantID
                  in: path
                  description: Tenant ID for the request
                  required: true
                  schema:
                    type: string
                    description: Tenant ID for the request
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                  example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                - name: recordID
                  in: path
                  description: ID of the record to retrieve
                  required: true
                  schema:
                    type: string
                    description: ID of the record to retrieve
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                  example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                - name: Authorization
                  in: header
                  description: JWT auth token
                  required: true
                  schema:
                    type: string
                    description: JWT auth token
                    example: Molestiae ab ipsa fuga.
                  example: Molestiae ab ipsa fuga.
            requestBody:
                description: Request body for get.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GetRequestBody'
                        example:
                            spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                            traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponseBody'
                            example:
                                cachedAt: Omnis impedit sed.
                                duration: 178461644483448189
                                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                                processedAt: Eius mollitia illo quia consequatur voluptatem.
                                retryCount: 5007217583026942089
                                retryDuration: 587659532169267737
                                status: 3494638038445428863
                                tenant: Numquam est voluptates dolor.
                                value: Quis nesciunt maiores quia ab.
                "404":
                    description: 'NotFound: Record not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                            example:
                                fault: false
                                id: 123abc
                                message: parameter 'p' must be an integer
                                name: NotFound
                                temporary: false
                                timeout: false
                "503":
                    description: 'Unavailable: Temporary error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                            example:
                                fault: false
                                id: 123abc
                                message: parameter 'p' must be an integer
                                name: Unavailable
                                temporary: true
                                timeout: false
    /records/{tenantID}/stream:
        get:
            tags:
                - interceptors
            summary: stream interceptors
            description: Stream records
            operationId: interceptors#stream
            parameters:
                - name: tenantID
                  in: path
                  description: Tenant ID for the request
                  required: true
                  schema:
                    type: string
                    description: Tenant ID for the request
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                  example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                - name: Authorization
                  in: header
                  description: JWT auth token
                  required: true
                  schema:
                    type: string
                    description: JWT auth token
                    example: Dolore repellendus sint soluta tenetur omnis.
                  example: Dolore repellendus sint soluta tenetur omnis.
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StreamResponseBody'
                            example:
                                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                                spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                                status: 3451733167122626757
                                tenant: Accusantium facilis est et.
                                traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                                value: Et qui.
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                value:
                    type: string
                    description: Value to store in record
                    example: Vel dolores.
            description: Request body for create.
            example:
                spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                value: Vel dolores.
            required:
                - value
        CreateResponseBody:
            type: object
            properties:
                duration:
                    type: integer
                    description: Processing duration in ms
                    example: 3718795145732531204
                    format: int64
                id:
                    type: string
                    description: ID of the created record
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                processedAt:
                    type: string
                    description: Timestamp when processed
                    example: Dolor sit.
                retryCount:
                    type: integer
                    description: Number of retry attempts made
                    example: 5419496228293178792
                    format: int64
                retryDuration:
                    type: integer
                    description: Total time spent retrying
                    example: 9203795670612989877
                    format: int64
                status:
                    type: integer
                    description: Response status code
                    example: 4185462404774819293
                    format: int64
                tenant:
                    type: string
                    description: Tenant the record belongs to
                    example: Dolores sunt non.
                value:
                    type: string
                    description: Value of the record
                    example: Minima eos voluptate esse dolores assumenda.
            example:
                duration: 3718795145732531204
                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                processedAt: Dolor sit.
                retryCount: 5419496228293178792
                retryDuration: 9203795670612989877
                status: 4185462404774819293
                tenant: Dolores sunt non.
                value: Minima eos voluptate esse dolores assumenda.
            required:
                - id
                - value
                - tenant
                - status
                - processedAt
                - duration
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Error response result type
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetRequestBody:
            type: object
            properties:
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
            description: Request body for get.
            example:
                spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
        GetResponseBody:
            type: object
            properties:
                cachedAt:
                    type: string
                    description: Time at which the record was cached, written by the Cache interceptor
                    example: Omnis impedit sed.
                duration:
                    type: integer
                    description: Processing duration in ms, written by the RequestAudit interceptor
                    example: 178461644483448189
                    format: int64
                id:
                    type: string
                    description: ID of the record
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                processedAt:
                    type: string
                    description: Timestamp when processed, written by the RequestAudit interceptor
                    example: Eius mollitia illo quia consequatur voluptatem.
                retryCount:
                    type: integer
                    description: Number of retry attempts made, written client-side by the Retry interceptor
                    example: 5007217583026942089
                    format: int64
                retryDuration:
                    type: integer
                    description: Total time spent retrying, written client-side by the Retry interceptor
                    example: 587659532169267737
                    format: int64
                status:
                    type: integer
                    description: Response status code
                    example: 3494638038445428863
                    format: int64
                tenant:
                    type: string
                    description: Tenant the record belongs to
                    example: Numquam est voluptates dolor.
                value:
                    type: string
                    description: Value of the record
                    example: Quis nesciunt maiores quia ab.
            example:
                cachedAt: Omnis impedit sed.
                duration: 178461644483448189
                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                processedAt: Eius mollitia illo quia consequatur voluptatem.
                retryCount: 5007217583026942089
                retryDuration: 587659532169267737
                status: 3494638038445428863
                tenant: Numquam est voluptates dolor.
                value: Quis nesciunt maiores quia ab.
            required:
                - id
                - value
                - tenant
                - status
                - processedAt
                - duration
        StreamResponseBody:
            type: object
            properties:
                id:
                    type: string
                    description: ID of the created record
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                status:
                    type: integer
                    description: Response status code
                    example: 3451733167122626757
                    format: int64
                tenant:
                    type: string
                    description: Tenant the record belongs to
                    example: Accusantium facilis est et.
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                value:
                    type: string
                    description: Value of the record
                    example: Et qui.
            example:
                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                status: 3451733167122626757
                tenant: Accusantium facilis est et.
                traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                value: Et qui.
            required:
                - id
                - value
                - tenant
                - status
        StreamStreamingBody:
            type: object
            properties:
                id:
                    type: string
                    description: ID of the created record
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                    format: uuid
                value:
                    type: string
                    description: Value of the record
                    example: Reprehenderit sunt nam veniam quibusdam.
            example:
                id: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                spanID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                traceID: dd11abcb-f3b1-412f-9ede-6f80730d5a28
                value: Reprehenderit sunt nam veniam quibusdam.
            required:
                - id
                - value
tags:
    - name: interceptors
      description: |-
        The interceptors service demonstrates a comprehensive use of interceptors combining
        authentication, tenant validation, caching, audit logging, and retry mechanisms. It showcases
        both client-side and server-side interceptors working together to provide a robust service.
